Test2
OpenSRDK/linear-algebra-rs pull request #72
Opened 2023-02-16 14:04 UTC by Ryo0731

2023-02-17 03:24 UTC, KimuraYu45z requested changes

2023-02-17 03:24 UTC, KimuraYu45z commented on src/tensor/sparse/operators/div.rs
> +        assert_eq!(res, rhs);
tensorまるごと比較するよりも一つ一つの要素確認してったほうが分かりやすいと思う
hash2のhashmapのinsertを直接取り扱うのは汚い

2023-02-17 03:24 UTC, KimuraYu45z commented on src/tensor/sparse/operators/mul.rs
> +        // cannot multiply &SparseTensor by Scalar
将来的にも借用テンソルとスカラーの倍算実装する予定ないです

2023-02-17 03:24 UTC, KimuraYu45z commented on src/tensor/sparse/operators/sub.rs
> +    // cannot work cos neg is not implemented yet
hashmapのinsert汚いので要素ごとにassert eqしよか
あとnegは難易度的に実装できる(要素のmutイテレータ使ってそれぞれneg演算子使うだけ)
addとか参考にやってみ

2023-02-17 08:46 UTC, KimuraYu45z commented on src/tensor/sparse/operators/sub.rs
> +    // cannot work cos neg is not implemented yet
よく考えたらmatrixのneg実装参考にしたら一発

2023-02-20 13:06 UTC, Ryo0731 commented on src/tensor/sparse/operators/div.rs
> +        assert_eq!(res, rhs);
>hash2のhashmapのinsertを直接取り扱うのは汚い

これってhashmap使わなうとしたらどう扱うのがいいですかね？

2023-02-21 05:24 UTC, KimuraYu45z commented on src/tensor/sparse/operators/div.rs
> +        assert_eq!(res, rhs);
lhsでやってるやり方でいいと思う

2023-02-21 14:55 UTC, KimuraYu45z approved these changes

2023-02-21 14:55 UTC, merged